#!/bin/bash
#
#------ Importation des fonctions---------
. ../Bash/fonctions/bashCentreTexteEtCouleurs
. ../Bash/fonctions/adduserEnSSH
. ../Bash/fonctions/deluserEnSSH
#
#------ Les variables---------------------
# elles sont vides pour le moment et seront modifier par le programme python.
nomUserSSH=""
hoteSSH=""
mdpUserSSH=""
nomNewUser=""
mpdNewUser=""
ncNewUser=""
nbNewUser=""
telProNewUser=""
telPersoNewUser=""
autreNewUser=""
#
# ----------- main -----------
#Le scrip python remplacera suivant le choix de l'utilisateur XXX1Commande par addUserBySSH ou delUserBySSH
#addUserBySSH
#delUserBySSH
XXX1Commande

