#!/bin/bash
# se connecte en ssh pour ajouter un nouvel utilisateur
# il faut absolument un nom d'utilisateur et ip ou dns pour le ssh et son mot de passe pour utiliser le sudo ( le mot de passe n'est pas demandé pour la connexion ssh )
#le nom de l'user a creer et son mdp a minima (nom complet, num bureau,tel pro,tel perso et autre sont optionnel)
#
#
addUserBySSH()
{
echo
centreTexteEtCouleurs "${blu}Connexion SSH vers ${hoteSSH} et Ajout de l'utilisateur ${nomNewUser}" "${cyn}="
#
if [ ${#nomUserSSH} = 0 ] || [ ${#hoteSSH} = 0 ] || [ ${#nomNewUser} = 0 ] || [ ${#nomNewUser} = 0 ] || [ ${#nomNewUser} = 0 ]
then
echoRouge "Il manque au moins un des parametres obligatoire pour l'ajout d'un utilisateur."
else
ssh ${nomUserSSH}@${hoteSSH} << eof
sudo -S adduser ${nomNewUser}
${mdpUserSSH}
${mpdNewUser}
${mpdNewUser}
${ncNewUser}
${nbNewUser}
${telProNewUser}
${telPersoNewUser}
${autreNewUser}
O
echo
exit
eof
fi
}

#
#    Programme permetant l'ajout d'utilisateur via une liste vers des postes d'une autre liste en SSH. Il est découpé en plusieurs fichiers
#    Copyright (C) 2021 Fay Thomas
#
#   Ce programme est un logiciel libre: vous pouvez le redistribuer et / ou le modifier
#    sous les termes de la licence publique générale GNU publiée par
#    la Free Software Foundation, soit la version 3 de la licence ou ulterieur.
#
#    Ce programme est distribué dans l'espoir qu'il sera utile,
#    mais SANS AUCUNE GARANTIE; sans même la garantie implicite de
#    QUALITÉ MARCHANDE ou ADAPTATION À UN USAGE PARTICULIER. Voir le
#    GNU General Public License pour plus de détails.
#
#    Licence disponible à la racine du projet.
#    Vous devriez avoir reçu une copie de la licence publique générale GNU
#    avec ce programme. Sinon, consultez <https://www.gnu.org/licenses/>.
